export enum Currency {
  // Major Global Currencies
  USD = 'USD',
  EUR = 'EUR',
  JPY = 'JPY',
  GBP = 'GBP',
  AUD = 'AUD',
  CAD = 'CAD',
  CHF = 'CHF',
  CNY = 'CNY',
  SEK = 'SEK',
  NZD = 'NZD',

  // Other Major Currencies
  NOK = 'NOK',
  DKK = 'DKK',
  SGD = 'SGD',
  HKD = 'HKD',
  KRW = 'KRW',
  INR = 'INR',
  BRL = 'BRL',
  RUB = 'RUB',
  MXN = 'MXN',
  ZAR = 'ZAR',

  // Middle East & Africa
  SAR = 'SAR',
  AED = 'AED',
  ILS = 'ILS',
  TRY = 'TRY',
  EGP = 'EGP',
  NGN = 'NGN',
  KES = 'KES',
  MAD = 'MAD',
  GHS = 'GHS',
  TND = 'TND',

  // Asia Pacific
  THB = 'THB',
  MYR = 'MYR',
  PHP = 'PHP',
  IDR = 'IDR',
  VND = 'VND',
  TWD = 'TWD',
  PKR = 'PKR',
  BDT = 'BDT',
  LKR = 'LKR',
  NPR = 'NPR',

  // Latin America
  CLP = 'CLP',
  COP = 'COP',
  PEN = 'PEN',
  ARS = 'ARS',
  UYU = 'UYU',
  BOB = 'BOB',
  PYG = 'PYG',
  VES = 'VES',
  CRC = 'CRC',
  GTQ = 'GTQ',

  // Eastern Europe
  PLN = 'PLN',
  CZK = 'CZK',
  HUF = 'HUF',
  RON = 'RON',
  BGN = 'BGN',
  HRK = 'HRK',
  RSD = 'RSD',
  UAH = 'UAH',

  // Other European
  ISK = 'ISK',

  // Central Asia & Others
  KZT = 'KZT',
  UZS = 'UZS',

  // Caribbean & Small Nations
  BBD = 'BBD',
  BMD = 'BMD',
  BSD = 'BSD',
  JMD = 'JMD',
  TTD = 'TTD',

  // Pacific
  FJD = 'FJD',
  PGK = 'PGK',

  // Africa continued
  BWP = 'BWP',
  MUR = 'MUR',
  SCR = 'SCR',
  SZL = 'SZL',
  LSL = 'LSL',
  NAD = 'NAD',
  ZMW = 'ZMW',
  MWK = 'MWK',
  UGX = 'UGX',
  TZS = 'TZS',
  RWF = 'RWF',
  ETB = 'ETB',

  // Middle East continued
  JOD = 'JOD',
  KWD = 'KWD',
  BHD = 'BHD',
  QAR = 'QAR',
  OMR = 'OMR',

  // Additional currencies
  AMD = 'AMD',
  GEL = 'GEL',
  AZN = 'AZN',
  MDL = 'MDL',
}

const countryToCurrencyMap: Record<string, Currency> = {
  US: Currency.USD,
  JP: Currency.JPY,
  GB: Currency.GBP,
  AU: Currency.AUD,
  CA: Currency.CAD,
  CH: Currency.CHF,
  CN: Currency.CNY,
  SE: Currency.SEK,
  NZ: Currency.NZD,
  NO: Currency.NOK,
  DK: Currency.DKK,
  SG: Currency.SGD,
  HK: Currency.HKD,
  KR: Currency.KRW,
  IN: Currency.INR,
  BR: Currency.BRL,
  RU: Currency.RUB,
  MX: Currency.MXN,
  ZA: Currency.ZAR,
  AT: Currency.EUR,
  BE: Currency.EUR,
  CY: Currency.EUR,
  EE: Currency.EUR,
  FI: Currency.EUR,
  FR: Currency.EUR,
  DE: Currency.EUR,
  GR: Currency.EUR,
  IE: Currency.EUR,
  IT: Currency.EUR,
  LV: Currency.EUR,
  LT: Currency.EUR,
  LU: Currency.EUR,
  MT: Currency.EUR,
  NL: Currency.EUR,
  PT: Currency.EUR,
  SK: Currency.EUR,
  SI: Currency.EUR,
  ES: Currency.EUR,
  HR: Currency.EUR,
  SA: Currency.SAR,
  AE: Currency.AED,
  IL: Currency.ILS,
  TR: Currency.TRY,
  EG: Currency.EGP,
  NG: Currency.NGN,
  KE: Currency.KES,
  MA: Currency.MAD,
  GH: Currency.GHS,
  TN: Currency.TND,
  TH: Currency.THB,
  MY: Currency.MYR,
  PH: Currency.PHP,
  ID: Currency.IDR,
  VN: Currency.VND,
  TW: Currency.TWD,
  PK: Currency.PKR,
  BD: Currency.BDT,
  LK: Currency.LKR,
  NP: Currency.NPR,
  CL: Currency.CLP,
  CO: Currency.COP,
  PE: Currency.PEN,
  AR: Currency.ARS,
  UY: Currency.UYU,
  BO: Currency.BOB,
  PY: Currency.PYG,
  VE: Currency.VES,
  CR: Currency.CRC,
  GT: Currency.GTQ,
  PL: Currency.PLN,
  CZ: Currency.CZK,
  HU: Currency.HUF,
  RO: Currency.RON,
  BG: Currency.BGN,
  RS: Currency.RSD,
  UA: Currency.UAH,
  IS: Currency.ISK,
  KZ: Currency.KZT,
  UZ: Currency.UZS,
  BB: Currency.BBD,
  BM: Currency.BMD,
  BS: Currency.BSD,
  JM: Currency.JMD,
  TT: Currency.TTD,
  FJ: Currency.FJD,
  PG: Currency.PGK,
  BW: Currency.BWP,
  MU: Currency.MUR,
  SC: Currency.SCR,
  SZ: Currency.SZL,
  LS: Currency.LSL,
  NA: Currency.NAD,
  ZM: Currency.ZMW,
  MW: Currency.MWK,
  UG: Currency.UGX,
  TZ: Currency.TZS,
  RW: Currency.RWF,
  ET: Currency.ETB,
  JO: Currency.JOD,
  KW: Currency.KWD,
  BH: Currency.BHD,
  QA: Currency.QAR,
  OM: Currency.OMR,
  AM: Currency.AMD,
  GE: Currency.GEL,
  AZ: Currency.AZN,
  MD: Currency.MDL,
}

export const getCurrencyFromCountryCode = (countryCode: string): Currency | undefined => {
  return countryToCurrencyMap[countryCode?.toUpperCase()]
}

export const getCurrencyFromIpData = (ipData: { country_code: string }): Currency | undefined => {
  return getCurrencyFromCountryCode(ipData.country_code)
}

export const detectCurrencyFromIp = async (apiKey: string, userIp?: string): Promise<Currency> => {
  try {
    const url = userIp 
      ? `http://api.ipapi.com/${userIp}?access_key=${apiKey}&format=1`
      : `http://api.ipapi.com/check?access_key=${apiKey}&format=1`
    
    const res = await fetch(url)
    const data = await res.json()
    
    const currency = getCurrencyFromCountryCode(data?.country_code)
    return currency || Currency.USD
  } catch (error) {
    console.error('Failed to detect currency from IP:', error)
    return Currency.USD
  }
}

export const getCurrencyDisplayName = (currency: Currency): string => {
  const displayNames: Record<Currency, string> = {
    [Currency.USD]: 'US Dollar ($)',
    [Currency.EUR]: 'Euro (€)',
    [Currency.JPY]: 'Japanese Yen (¥)',
    [Currency.GBP]: 'British Pound (£)',
    [Currency.AUD]: 'Australian Dollar (A$)',
    [Currency.CAD]: 'Canadian Dollar (C$)',
    [Currency.CHF]: 'Swiss Franc (CHF)',
    [Currency.CNY]: 'Chinese Yuan (¥)',
    [Currency.SEK]: 'Swedish Krona (kr)',
    [Currency.NZD]: 'New Zealand Dollar (NZ$)',
    [Currency.NOK]: 'Norwegian Krone (kr)',
    [Currency.DKK]: 'Danish Krone (kr)',
    [Currency.SGD]: 'Singapore Dollar (S$)',
    [Currency.HKD]: 'Hong Kong Dollar (HK$)',
    [Currency.KRW]: 'South Korean Won (₩)',
    [Currency.INR]: 'Indian Rupee (₹)',
    [Currency.BRL]: 'Brazilian Real (R$)',
    [Currency.RUB]: 'Russian Ruble (₽)',
    [Currency.MXN]: 'Mexican Peso ($)',
    [Currency.ZAR]: 'South African Rand (R)',
    [Currency.SAR]: 'Saudi Riyal (﷼)',
    [Currency.AED]: 'UAE Dirham (د.إ)',
    [Currency.ILS]: 'Israeli Shekel (₪)',
    [Currency.TRY]: 'Turkish Lira (₺)',
    [Currency.EGP]: 'Egyptian Pound (£)',
    [Currency.NGN]: 'Nigerian Naira (₦)',
    [Currency.KES]: 'Kenyan Shilling (KSh)',
    [Currency.MAD]: 'Moroccan Dirham (MAD)',
    [Currency.GHS]: 'Ghanaian Cedi (₵)',
    [Currency.TND]: 'Tunisian Dinar (TND)',
    [Currency.THB]: 'Thai Baht (฿)',
    [Currency.MYR]: 'Malaysian Ringgit (RM)',
    [Currency.PHP]: 'Philippine Peso (₱)',
    [Currency.IDR]: 'Indonesian Rupiah (Rp)',
    [Currency.VND]: 'Vietnamese Dong (₫)',
    [Currency.TWD]: 'Taiwan Dollar (NT$)',
    [Currency.PKR]: 'Pakistani Rupee (₨)',
    [Currency.BDT]: 'Bangladeshi Taka (৳)',
    [Currency.LKR]: 'Sri Lankan Rupee (₨)',
    [Currency.NPR]: 'Nepalese Rupee (₨)',
    [Currency.CLP]: 'Chilean Peso ($)',
    [Currency.COP]: 'Colombian Peso ($)',
    [Currency.PEN]: 'Peruvian Sol (S/)',
    [Currency.ARS]: 'Argentine Peso ($)',
    [Currency.UYU]: 'Uruguayan Peso ($)',
    [Currency.BOB]: 'Bolivian Boliviano (Bs)',
    [Currency.PYG]: 'Paraguayan Guarani (₲)',
    [Currency.VES]: 'Venezuelan Bolívar (Bs)',
    [Currency.CRC]: 'Costa Rican Colón (₡)',
    [Currency.GTQ]: 'Guatemalan Quetzal (Q)',
    [Currency.PLN]: 'Polish Zloty (zł)',
    [Currency.CZK]: 'Czech Koruna (Kč)',
    [Currency.HUF]: 'Hungarian Forint (Ft)',
    [Currency.RON]: 'Romanian Leu (lei)',
    [Currency.BGN]: 'Bulgarian Lev (лв)',
    [Currency.HRK]: 'Croatian Kuna (kn)',
    [Currency.RSD]: 'Serbian Dinar (дин)',
    [Currency.UAH]: 'Ukrainian Hryvnia (₴)',
    [Currency.ISK]: 'Icelandic Krona (kr)',
    [Currency.KZT]: 'Kazakhstani Tenge (₸)',
    [Currency.UZS]: 'Uzbekistani Som (UZS)',
    [Currency.BBD]: 'Barbadian Dollar (BBD)',
    [Currency.BMD]: 'Bermudian Dollar (BMD)',
    [Currency.BSD]: 'Bahamian Dollar (BSD)',
    [Currency.JMD]: 'Jamaican Dollar (J$)',
    [Currency.TTD]: 'Trinidad and Tobago Dollar (TTD)',
    [Currency.FJD]: 'Fijian Dollar (FJD)',
    [Currency.PGK]: 'Papua New Guinea Kina (PGK)',
    [Currency.BWP]: 'Botswana Pula (P)',
    [Currency.MUR]: 'Mauritian Rupee (₨)',
    [Currency.SCR]: 'Seychellois Rupee (₨)',
    [Currency.SZL]: 'Swazi Lilangeni (SZL)',
    [Currency.LSL]: 'Lesotho Loti (LSL)',
    [Currency.NAD]: 'Namibian Dollar (NAD)',
    [Currency.ZMW]: 'Zambian Kwacha (ZMW)',
    [Currency.MWK]: 'Malawian Kwacha (MWK)',
    [Currency.UGX]: 'Ugandan Shilling (UGX)',
    [Currency.TZS]: 'Tanzanian Shilling (TZS)',
    [Currency.RWF]: 'Rwandan Franc (RWF)',
    [Currency.ETB]: 'Ethiopian Birr (ETB)',
    [Currency.JOD]: 'Jordanian Dinar (JOD)',
    [Currency.KWD]: 'Kuwaiti Dinar (KWD)',
    [Currency.BHD]: 'Bahraini Dinar (BHD)',
    [Currency.QAR]: 'Qatari Riyal (QAR)',
    [Currency.OMR]: 'Omani Rial (OMR)',
    [Currency.AMD]: 'Armenian Dram (AMD)',
    [Currency.GEL]: 'Georgian Lari (₾)',
    [Currency.AZN]: 'Azerbaijani Manat (₼)',
    [Currency.MDL]: 'Moldovan Leu (MDL)',
  }

  return displayNames[currency] || currency
}
