import {
  Award,
  Briefcase,
  Building,
  Car,
  Coffee,
  CreditCard,
  Crown,
  Diamond,
  DollarSign,
  Gamepad2,
  Gift,
  Heart,
  Home,
  Loader,
  Music,
  Phone,
  PiggyBank,
  Plus,
  ShoppingCart,
  Star,
  Target,
  TrendingUp,
  Users,
  Utensils,
  Wallet,
  Zap,
} from 'lucide-react'

// Predefined icons to choose from in categories page
const iconOptions = [
  { name: 'DollarSign', icon: DollarSign },
  { name: 'Home', icon: Home },
  { name: 'Car', icon: Car },
  { name: 'ShoppingCart', icon: ShoppingCart },
  { name: 'Utensils', icon: Utensils },
  { name: 'Gamepad2', icon: Gamepad2 },
  { name: 'Phone', icon: Phone },
  { name: 'CreditCard', icon: CreditCard },
  { name: 'TrendingUp', icon: TrendingUp },
  { name: 'Gift', icon: Gift },
  { name: 'Award', icon: Award },
  { name: 'Briefcase', icon: Briefcase },
  { name: 'Building', icon: Building },
  { name: 'Coffee', icon: Coffee },
  { name: 'Music', icon: Music },
  { name: 'Heart', icon: Heart },
  { name: 'Zap', icon: Zap },
  { name: 'Wallet', icon: Wallet },
  { name: 'PiggyBank', icon: PiggyBank },
  { name: 'Target', icon: Target },
  { name: 'Users', icon: Users },
  { name: 'Star', icon: Star },
  { name: 'Crown', icon: Crown },
  { name: 'Diamond', icon: Diamond },
]

export { iconOptions }
